= What is a programming language

== Definition 1
* A programming language is a formal language that specifies a set of instructions that can be used to produce various kinds of output. Programming languages generally consist of instructions for a computer. Programming languages can be used to create programs that implement specific algorithms. xref:sources[1]

* A formal language is a set of strings of symbols together with a set of rules that are specific to it.

* An instruction is a way to tell a computer to do something. Instructions are usually simple math or logic operations.

* A computer is a device that take a sequence of math or logic operations and perform them.

== Definition 2
* A programming language is a notation for writing programs, which are specifications of a computation or algorithm.



== Definition 3
* A complete description of a programming language includes the computational model, the syntax and semantics of programs, and the pragmatic considerations that shape the language. xref:sources[5]
