= What is a Programming Language

== Definition 1
A programming language is a formal language that specifies a set of instructions that can be used to produce various kinds of output.

Programming languages generally consist of instructions for a computer.

Programming languages can be used to create programs that implement specific algorithms. xref:sources[1]

Formal Language:: Set of strings of symbols together with a set of rules that are specific to it.

Instruction:: A way to tell a computer to do something. Instructions are usually simple math or logic operations.

Computer:: A device that takes a sequence of math or logic operations and perform them.

== Definition 2
A programming language is a notation for writing programs.

Programs:: Specifications of a computation or algorithm.

Algorithm:: Unambiguous way to solve a problem.

Computation:: A calculation, involving mathematical and/or non-mathematical steps and a well-defined model. For example, an algorithm.


== Definition 3
A complete description of a programming language includes the computational model, the syntax and semantics of programs, and the pragmatic considerations that shape the language. xref:sources[5]

Computational Model:: A set of value and operations allowed in the language.

Syntax:: Structure and form of the language. (Notation)

Semantics:: The relationship between the syntax and the computational model.

Pragmatic Considerations:: How well the programming language accomplishes its goal.


== Simple Explanation
A programming language is a way to tell some form of a computer how to do work which involves algorithms, math, logic, and other instructions.

Examples of languages:

.Assembly
[source,assembly]
----
something
----

.C
[source,c]
----
something
----

.Java
[source,java]
----
something
----

.Python
[source,python]
----
something
----

.Ruby
[source,ruby]
----
something
----

.Lisp
[source,lisp]
----
something
----

.Swift
[source,swift]
----
something
----

.Javascript
[source,javascript]
----
something
----

And link:https://en.wikipedia.org/wiki/List_of_programming_languages[a lot more].
