= Computational model

link:http://www.emu.edu.tr/aelci/Courses/D-318/D-318-Files/plbook/intro.htm[Source^]

A set of values and operations allowed in the language.

== Values
* Pieces of data
** `10`, `h`, `Computer Science`, `(1,2)`

== Operations
* A piece of work done by a computer, usually involving values
//* An instruction is a discrete operation as part of an instruction set
//* An instruction set is the limited set of instructions that a computer can perform.
* A computation is an application of a sequence of operations to a value to yield another value.


== Example

We have a language that services performing the four basic math operations on two numbers:

* Add
* Subtract
* Multiply
* Divide

What could the computational model look like?

=== Option 1

Values:: Integers (INT)
Operations:: `INT + INT` , `INT - INT` , `INT * INT` , `INT / INT`

.Example Usage
[source]
----
1 + 0
5 - 3
4 * 6
8 / 2
----

=== Option 2

Values:: Integers (INT), Natural Numbers (NAT)
Operations:: `INT + INT` , `INT - INT` , `Repeat[INT + INT|NAT]` , `CountRepeatsUntilZero[INT - INT]`

.Example Usage
[source]
----
1 + 0
5 - 3
Repeat[6 + 6|4]
CountRepeatsUntilZero[8 - 2]
----

== Exercises
. What is another computational model for the above example?
. What would 2 computational models be for doing squaring (e.g 5^2^)?
. What would 2 computational models be for doing general exponents (e.g. 3^4^)?
