= What is Not a Programming Language

== Defining the Problem
There exist languages that allow you to do some limited set of work, but are not programming languages.

For example, languages, such as HTML, Markdown, JSON, YAML, and XML are considered markup languages and _NOT_ programming languages.


== Markup Languages
* Markup Languages define structured data link:https://github.com/rhoads-zach/programming-languages-cirriculum/blob/master/adoc/topics/sources.adoc[6], but are not programming languages.
* Markup languages are purpose built to:
** Create or annotate documents
** Enable Data Transport
* Markup languages cannot be used to implement algorithms.

=== Right Tool, Right Job
* Markup languages are intentionally restrictive to allow a focus on the purpose
* They are not ways to solve general programming problems
* They focus on a specific task

== Example Uses

=== HTML
* HTML focuses on displaying structured text

.Example HTML
[source,html]
----
<html>
  <head></head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
----

=== Markdown
* Markdown focuses on a way to create structured, but in a more simplified way.
* It provides a _subset_ of the capabilities of HTML, with the focus on writing prose

.Example Markdown
[source,markdown]
----
= Hello, World!
----

=== JSON and XML
* JSON and XML focus on providing machine-readable structured data
* Works very well for data storage and transport
* Think RESTful and Web services

=== Example JSON
[source,json]
----
{
  "greeting" : "Hello, World!"
}
----

=== Example XML
[source,xml]
----
<xml>
  <greeting>Hello, World!</greeting>
</xml>
----

=== YAML
* YAML focuses on providing machine readable structured data, but is frequently used for configuration files

.Example YAML
[source,yaml]
----
greeting: Hello, World!
----

== Hybrid Languages

* Hybrid languages combine concepts of markup languages with a subset of programming language functionality link:https://github.com/rhoads-zach/programming-languages-cirriculum/blob/master/adoc/topics/sources.adoc[5].
** iteration
** if statements
* If you want to focus on displaying structured data, but you want a bit more functionality.
* Examples: JSP, XSLT, Asciidoc

=== Example Uses
* JSP provides the ability to write html, with the ability to create macros and add Java directly to the page.
** The code is executed on the server before the final HTML is sent as a response
* XSLT focuses on data transformation
* Asciidoc provides a superset of markdown functionality, but also gives things like if statements and property replacement.
