= What is a Programming Language

== Definition 1
* A programming language is a formal language that specifies a set of instructions that can be used to produce various kinds of output.
* Programming languages generally consist of instructions for a computer.
* Programming languages can be used to create programs that implement specific algorithms. link:https://github.com/rhoads-zach/programming-languages-cirriculum/blob/master/adoc/topics/sources.adoc[^1^]

=== Definition 1 - Terms
* _Formal Language_ : Set of strings of symbols together with a set of rules that are specific to it.
* _Instruction_ : A way to tell a computer to do something. Instructions are usually simple math or logic operations.
* _Computer_ : A device that takes a sequence of math or logic operations and perform them.

== Definition 2
* A programming language is a notation for writing programs.

.Terms
* _Programs_: Specifications of a computation or algorithm.
* _Algorithm_: Unambiguous way to solve a problem.
* _Computation_: A calculation, involving mathematical and/or non-mathematical steps and a well-defined model. For example, an algorithm.


== Definition 3
* A complete description of a programming language includes the computational model, the syntax and semantics of programs, and the pragmatic considerations that shape the language. link:https://github.com/rhoads-zach/programming-languages-cirriculum/blob/master/adoc/topics/sources.adoc[^5^]

.Terms
* _Computational Model_: A set of value and operations allowed in the language.
* _Syntax_: Structure and form of the language. (Notation)
* _Semantics_: The relationship between the syntax and the computational model.
* _Pragmatic Considerations_: How well the programming language accomplishes its goal.


== Simple Explanation
A programming language is a way to tell some form of a computer how to do work which involves algorithms, math, logic, and other instructions.

== Examples of Languages

=== Assembly
.link:https://github.com/leachim6/hello-world/blob/master/a/assembler_nasm_linux.asm[Example Assembly^]
[source]
----
section	.text
    global _start			;must be declared for linker (ld)

_start:					;tell linker entry point

	xor	ebx,ebx 	;ebx=0
	mov	ecx,msg		;address of message to write
	lea	edx,[ebx+len]	;message length
	lea	eax,[ebx+4]	;system call number (sys_write)
	inc	ebx		;file descriptor (stdout)
	int	0x80		;call kernel

	xor	eax, eax	;set eax=0
	inc	eax		;system call number (sys_exit)
	int	0x80		;call kernel

section	.rodata

msg	db	'Hello, world!',0xa	;our string
len	equ	$ - msg			;length of our string
----

=== C
.link:https://github.com/leachim6/hello-world/blob/master/c/c.c[Example C^]
[source,c]
----
#include <stdio.h>

int main() {
	printf("Hello World\n");
	return 0;
}
----

=== Java
.link:https://github.com/leachim6/hello-world/blob/master/j/Java.java[Example Java^]
[source,java]
----
public class Java {
	public static void main(String[] args) {
		System.out.println("Hello World");
	}
}
----

=== Python
.link:https://github.com/leachim6/hello-world/blob/master/p/python.py[Example Python^]
[source,python]
----
#!/usr/bin/env python
print "Hello World"
----

=== Ruby
.link:https://github.com/leachim6/hello-world/blob/master/r/ruby.rb[Example Ruby^]
[source,ruby]
----
#!/usr/bin/env ruby
puts "Hello World"
----

=== Lisp
.link:https://github.com/leachim6/hello-world/blob/master/l/lisp.lsp[Example Lisp^]
[source]
----
; LISP
(DEFUN hello ()
  (PRINT (LIST 'HELLO 'WORLD))
)

(hello)
----

=== JavaScript
.link:https://github.com/leachim6/hello-world/blob/master/j/javascript.js[Example JavaScript^]
[source,javascript]
----
console.log("Hello World");
----

=== More
And link:https://en.wikipedia.org/wiki/List_of_programming_languages[a lot more languages^] and link:https://github.com/leachim6/hello-world[examples^].
